#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : infiniband-diags
Version  : 2.1.0
Release  : 6
URL      : https://github.com/linux-rdma/infiniband-diags/releases/download/2.1.0/infiniband-diags-2.1.0.tar.gz
Source0  : https://github.com/linux-rdma/infiniband-diags/releases/download/2.1.0/infiniband-diags-2.1.0.tar.gz
Summary  : OpenFabrics Alliance InfiniBand Diagnostic Tools
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0
Requires: infiniband-diags-bin
Requires: infiniband-diags-lib
Requires: infiniband-diags-license
Requires: infiniband-diags-man
Requires: infiniband-diags-data
BuildRequires : opensm-dev
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : rdma-core-dev

%description
This package provides IB diagnostic programs and scripts needed to diagnose an
IB subnet.  infiniband-diags now also provides libibmad.  libibmad provides low
layer IB functions for use by the IB diagnostic and management programs. These
include MAD, SA, SMP, and other basic IB functions.

%package bin
Summary: bin components for the infiniband-diags package.
Group: Binaries
Requires: infiniband-diags-data
Requires: infiniband-diags-license
Requires: infiniband-diags-man

%description bin
bin components for the infiniband-diags package.


%package data
Summary: data components for the infiniband-diags package.
Group: Data

%description data
data components for the infiniband-diags package.


%package dev
Summary: dev components for the infiniband-diags package.
Group: Development
Requires: infiniband-diags-lib
Requires: infiniband-diags-bin
Requires: infiniband-diags-data
Provides: infiniband-diags-devel

%description dev
dev components for the infiniband-diags package.


%package lib
Summary: lib components for the infiniband-diags package.
Group: Libraries
Requires: infiniband-diags-data
Requires: infiniband-diags-license

%description lib
lib components for the infiniband-diags package.


%package license
Summary: license components for the infiniband-diags package.
Group: Default

%description license
license components for the infiniband-diags package.


%package man
Summary: man components for the infiniband-diags package.
Group: Default

%description man
man components for the infiniband-diags package.


%prep
%setup -q -n infiniband-diags-2.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534111767
%configure --disable-static --with-perl-installdir=/usr/share/perl5
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1534111767
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/infiniband-diags
cp COPYING %{buildroot}/usr/share/doc/infiniband-diags/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/check_lft_balance.pl
/usr/bin/dump_fts
/usr/bin/dump_lfts.sh
/usr/bin/dump_mfts.sh
/usr/bin/ibaddr
/usr/bin/ibcacheedit
/usr/bin/ibccconfig
/usr/bin/ibccquery
/usr/bin/ibfindnodesusing.pl
/usr/bin/ibhosts
/usr/bin/ibidsverify.pl
/usr/bin/iblinkinfo
/usr/bin/ibnetdiscover
/usr/bin/ibnodes
/usr/bin/ibping
/usr/bin/ibportstate
/usr/bin/ibqueryerrors
/usr/bin/ibroute
/usr/bin/ibrouters
/usr/bin/ibstat
/usr/bin/ibstatus
/usr/bin/ibswitches
/usr/bin/ibsysstat
/usr/bin/ibtracert
/usr/bin/perfquery
/usr/bin/saquery
/usr/bin/sminfo
/usr/bin/smpdump
/usr/bin/smpquery
/usr/bin/vendstat

%files data
%defattr(-,root,root,-)
/usr/share/perl5/IBswcountlimits.pm

%files dev
%defattr(-,root,root,-)
/usr/include/infiniband/ibnetdisc.h
/usr/include/infiniband/ibnetdisc_osd.h
/usr/include/infiniband/mad.h
/usr/include/infiniband/mad_osd.h
/usr/lib64/libibmad.so
/usr/lib64/libibnetdisc.so
/usr/share/man/man3/ibnd_debug.3
/usr/share/man/man3/ibnd_destroy_fabric.3
/usr/share/man/man3/ibnd_discover_fabric.3
/usr/share/man/man3/ibnd_find_node_dr.3
/usr/share/man/man3/ibnd_find_node_guid.3
/usr/share/man/man3/ibnd_iter_nodes.3
/usr/share/man/man3/ibnd_iter_nodes_type.3
/usr/share/man/man3/ibnd_show_progress.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libibmad.so.5
/usr/lib64/libibmad.so.5.5.0
/usr/lib64/libibnetdisc.so.5
/usr/lib64/libibnetdisc.so.5.3.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/infiniband-diags/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man8/check_lft_balance.8
/usr/share/man/man8/dump_fts.8
/usr/share/man/man8/dump_lfts.8
/usr/share/man/man8/dump_mfts.8
/usr/share/man/man8/ibaddr.8
/usr/share/man/man8/ibcacheedit.8
/usr/share/man/man8/ibccconfig.8
/usr/share/man/man8/ibccquery.8
/usr/share/man/man8/ibfindnodesusing.8
/usr/share/man/man8/ibhosts.8
/usr/share/man/man8/ibidsverify.8
/usr/share/man/man8/iblinkinfo.8
/usr/share/man/man8/ibnetdiscover.8
/usr/share/man/man8/ibnodes.8
/usr/share/man/man8/ibping.8
/usr/share/man/man8/ibportstate.8
/usr/share/man/man8/ibqueryerrors.8
/usr/share/man/man8/ibroute.8
/usr/share/man/man8/ibrouters.8
/usr/share/man/man8/ibstat.8
/usr/share/man/man8/ibstatus.8
/usr/share/man/man8/ibswitches.8
/usr/share/man/man8/ibsysstat.8
/usr/share/man/man8/ibtracert.8
/usr/share/man/man8/infiniband-diags.8
/usr/share/man/man8/perfquery.8
/usr/share/man/man8/saquery.8
/usr/share/man/man8/sminfo.8
/usr/share/man/man8/smpdump.8
/usr/share/man/man8/smpquery.8
/usr/share/man/man8/vendstat.8
