#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : infiniband-diags
Version  : 2.0.0
Release  : 1
URL      : https://github.com/linux-rdma/infiniband-diags/archive/2.0.0.tar.gz
Source0  : https://github.com/linux-rdma/infiniband-diags/archive/2.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: infiniband-diags-bin
Requires: infiniband-diags-lib
Requires: infiniband-diags-doc
BuildRequires : opensm-dev
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : rdma-core-dev

%description
InfiniBand Diagnostic Tools
infiniband-diags is a set of utilities designed to help configure, debug, and
maintain infiniband fabrics.  Many tools and utilities are provided.  Some with
similar functionality.

%package bin
Summary: bin components for the infiniband-diags package.
Group: Binaries

%description bin
bin components for the infiniband-diags package.


%package dev
Summary: dev components for the infiniband-diags package.
Group: Development
Requires: infiniband-diags-lib
Requires: infiniband-diags-bin
Provides: infiniband-diags-devel

%description dev
dev components for the infiniband-diags package.


%package doc
Summary: doc components for the infiniband-diags package.
Group: Documentation

%description doc
doc components for the infiniband-diags package.


%package lib
Summary: lib components for the infiniband-diags package.
Group: Libraries

%description lib
lib components for the infiniband-diags package.


%prep
%setup -q -n infiniband-diags-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1506720532
%autogen --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1506720532
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/IBswcountlimits.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/check_lft_balance.pl
/usr/bin/dump_fts
/usr/bin/dump_lfts.sh
/usr/bin/dump_mfts.sh
/usr/bin/ibaddr
/usr/bin/ibcacheedit
/usr/bin/ibccconfig
/usr/bin/ibccquery
/usr/bin/ibfindnodesusing.pl
/usr/bin/ibhosts
/usr/bin/ibidsverify.pl
/usr/bin/iblinkinfo
/usr/bin/ibnetdiscover
/usr/bin/ibnodes
/usr/bin/ibping
/usr/bin/ibportstate
/usr/bin/ibqueryerrors
/usr/bin/ibroute
/usr/bin/ibrouters
/usr/bin/ibstat
/usr/bin/ibstatus
/usr/bin/ibswitches
/usr/bin/ibsysstat
/usr/bin/ibtracert
/usr/bin/perfquery
/usr/bin/saquery
/usr/bin/sminfo
/usr/bin/smpdump
/usr/bin/smpquery
/usr/bin/vendstat

%files dev
%defattr(-,root,root,-)
/usr/include/infiniband/ibnetdisc.h
/usr/include/infiniband/ibnetdisc_osd.h
/usr/include/infiniband/mad.h
/usr/include/infiniband/mad_osd.h
/usr/lib64/libibmad.so
/usr/lib64/libibnetdisc.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libibmad.so.5
/usr/lib64/libibmad.so.5.5.0
/usr/lib64/libibnetdisc.so.5
/usr/lib64/libibnetdisc.so.5.3.0
